import { Vehicle } from '@/types/vehicle';

const now = new Date().toISOString();

export const demoVehicles: Vehicle[] = [
  {
    id: 'demo-toyota-rav4',
    plate: 'TSRV-101',
    make: 'Toyota',
    model: 'RAV4',
    year: 2024,
    color: 'Blanco',
    type: 'suv',
    seats: 5,
    transmission: 'automatic',
    fuel_type: 'hybrid',
    daily_price: 62000,
    mileage: 8400,
    status: 'available',
    purchase_date: '2024-03-15',
    insurance_expiry: '2027-03-15',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-suzuki-jimny',
    plate: 'TSRV-102',
    make: 'Suzuki',
    model: 'Jimny',
    year: 2023,
    color: 'Verde',
    type: 'suv',
    seats: 4,
    transmission: 'manual',
    fuel_type: 'gasoline',
    daily_price: 48000,
    mileage: 12650,
    status: 'available',
    purchase_date: '2023-08-10',
    insurance_expiry: '2026-08-10',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-hyundai-sonata',
    plate: 'TSRV-103',
    make: 'Hyundai',
    model: 'Sonata',
    year: 2024,
    color: 'Gris',
    type: 'sedan',
    seats: 5,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    daily_price: 54000,
    mileage: 6200,
    status: 'available',
    purchase_date: '2024-05-20',
    insurance_expiry: '2027-05-20',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-kia-sportage',
    plate: 'TSRV-104',
    make: 'Kia',
    model: 'Sportage',
    year: 2025,
    color: 'Azul',
    type: 'suv',
    seats: 5,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    daily_price: 67000,
    mileage: 1800,
    status: 'available',
    purchase_date: '2025-01-12',
    insurance_expiry: '2028-01-12',
    created_at: now,
    updated_at: now,
  },
];

export function findDemoVehicle(vehicleId: string): Vehicle | null {
  return demoVehicles.find((vehicle) => vehicle.id === vehicleId) ?? null;
}
